### ISSUE TITLE
The application closed itself

### ISSUE THREAD

**Issue by martikyan** [Zipliks/rmod#1]
After hitting the download button and minimizing the application it just closed.

Random steps to reproduce

**Comment by martikyan** [comment]
> After hitting the download button and minimizing the application it just closed.
> 
> Random steps to reproduce

It closed after a couple of minutes not immediately

**Comment by zipliks** [comment]
> > After hitting the download button and minimizing the application it just closed.
> > Random steps to reproduce
> 
> It closed after a couple of minutes not immediately

Does it closes even if you idling?

P.S. We are working on a recode version, hope it will work better

**Comment by martikyan** [comment]
Haven't tried doing "idling", but I hope it'd work in the newer release.

**Comment by martikyan** [comment]
> > > After hitting the download button and minimizing the application it just closed.
> > > Random steps to reproduce
> > 
> > 
> > It closed after a couple of minutes not immediately
> 
> Does it closes even if you idling?
> 
> P.S. We are working on a recode version, hope it will work better

As I see it's the 2nd redesign upcoming? 😆

**Comment by zipliks** [comment]
> > > > After hitting the download button and minimizing the application it just closed.
> > > > Random steps to reproduce
> > > 
> > > 
> > > It closed after a couple of minutes not immediately
> > 
> > 
> > Does it closes even if you idling?
> > P.S. We are working on a recode version, hope it will work better
> 
> As I see it's the 2nd redesign upcoming? 😆

I'd like to call it recode, because it will be absolutely new programming language and, i hope, we could improve its stability and functionality :^)
