### ISSUE TITLE
Only the "broken; use archive" inside "I want" selector

### ISSUE THREAD

**Issue by Lauriero** [Zipliks/rmod#2]
You seem to full your "I want" selector with data parsed from JSON from this URL - "https://gist.githubusercontent.com/Zipliks/ccffd954c6a687f3b7b54a60bd6a12f5/raw/updater".
But now, "broken; use archive" is inside every item of "main_arr" array.

**Comment by Lauriero** [comment]
Как оказалось я мог писать и на своем родном языке, так что если так вам будет проще, то по ссылке, с которой вы берете json с языками и ссылками на файлы ("https://gist.githubusercontent.com/Zipliks/ccffd954c6a687f3b7b54a60bd6a12f5/raw/updater"), я вижу json, где массив main_arr заполнен "broken; use archive" значениями по ключу lang

**Comment by zipliks** [comment]
Так и есть
Это сделано для того, чтобы гении мысли не качали языки, которые ещё не готовы (German, Japanese)

Как только файлы будут залиты хоть куда-нибудь на FTP/хостинг, то эти "заглушки" будут сняты
Но пока у нас проблемы с хостингом...
